### ISSUE TITLE
Bug pdf sous Firefox 60.8.0esr

### ISSUE THREAD

**Issue by alexandre-leonardi** [Envinorma/envinorma-web#118]
60.8.0esr (32 bits)
Ministère-Transition-Ecologique-Solidaire-1.6 (CCK2)

[Arnaud Lavérie sur Fééric]

En lisant ta réponse, j'ai compris que j'étais censé pouvoir ouvrir les AP... 🤔.
Après 10 mn à galérer, j'ai changé de navigateur et oh miracle, ça marche tout seul.
Bref, chez moi ça marche très bien sur Chrome mais sur Firefox la fenêtre de visualisation des pdf ne s'affiche pas (et si j'écoute mon service info, je suis censé n'utiliser que Firefox 😇)

**Comment by lisa-durand** [comment]
Hmm très étonnant - le plus simple serait qu'on puisse discuter en direct avec cet inspecteur avec le partage d'ecran car j'ai téléchargé la mm version de Firefox et je n'ai pas rencontré de souci.

<img width="1051" alt="Capture d’écran 2021-05-19 à 12 45 19" src="https://user-images.githubusercontent.com/6756627/118800755-8de7f800-b8a0-11eb-91f4-cef7c2968b64.png">
