### ISSUE TITLE
[Nouvelle Installation] améliorer l'ajout du classement avec une table de reference de nomenclature

### ISSUE THREAD

**Issue by lisa-durand** [Envinorma/envinorma-web#178]
- [x] ajouter l'alinea
- [x] faire de l'autocompletion pour remplir rubrique / regime / alinea / activite avec un seul champ
- [x] https://github.com/Envinorma/data-tasks/issues/12
- [ ] after party task

**Comment by remidbs** [comment]
<details>
<summary>Liste exhaustive des classements en vigueur</summary>

rubrique | regime | alinea
---------|--------|-------
1185 | A | 1a
1185 | D | 2a
1185 | D | 31a
1185 | D | 32
1185 | D | 2b
1185 | D | 31b
1185 | D | 1b
1185 | NC | 3
1185 | NC | 1
1185 | NC | 31
1185 | NC | 
1185 | NC | 2
1312 | A | 
1413 | A | 1a
1413 | A | 2a
1413 | D | 2b
1413 | D | 1b
1413 | NC | 1
1413 | NC | 
1413 | NC | Nota
1413 | NC | 2
1414 | A | 2b
1414 | A | 4
1414 | A | 2c
1414 | A | 1
1414 | A | 2a
1414 | D | 3
1414 | D | 2d
1414 | NC | 
1414 | NC | 2
1416 | D | 
1421 | A | 1
1421 | A | 2
1421 | NC | 
1434 | A | 1a
1434 | A | 2
1434 | D | 1b
1434 | NC | 1
1434 | NC | 
1435 | D | 2
1435 | E | 1
1435 | NC | 
1435 | NC | Nota
1436 | A | 1
1436 | D | 2
1436 | NC | 
1450 | A | 1
1450 | D | 2
1450 | NC | 
1455 | D | 
1510 | A | 1
1510 | A | 2a
1510 | D | 2c
1510 | E | 2b
1510 | NC | 
1510 | NC | 2
1510 | NC | NOTA
1511 | D | 2
1511 | E | 1
1511 | NC | 
1511 | NC | NOTA
1530 | D | 2
1530 | E | 1
1530 | NC | 
1531 | D | 
1532 | A | 1
1532 | D | 2b
1532 | E | 2a
1532 | NC | 
1532 | NC | 2
1630 | A | 1
1630 | D | 2
1630 | NC | 
1700 | NC | 
1716 | A | 1
1716 | D | 2
1716 | NC | 
1716 | NC | Nota
1735 | A | 
1978 | D | 20
1978 | D | 11
1978 | D | 2
1978 | D | 18
1978 | D | 13
1978 | D | 8
1978 | D | 14
1978 | D | 5
1978 | D | 10
1978 | D | 19
1978 | D | 3a
1978 | D | 15
1978 | D | 17
1978 | D | 4
1978 | D | 3b
1978 | D | 16
1978 | D | 6
1978 | D | 7
1978 | D | 9
1978 | D | 12
1978 | D | 1
1978 | NC | NOTA
1978 | NC | 
1978 | NC | 3
2101 | A | 2a
2101 | A | 1a
2101 | D | 2c
2101 | D | 1c
2101 | D | 3
2101 | D | 4
2101 | E | 2b
2101 | E | 1b
2101 | NC | 1
2101 | NC | 
2101 | NC | 2
2102 | D | 2
2102 | E | 1
2102 | NC | 
2102 | NC | Nota
2110 | A | 1
2110 | D | 2
2110 | NC | 
2111 | D | 2
2111 | E | 1
2111 | NC | 
2111 | NC | Nota
2112 | D | 
2113 | A | 1
2113 | D | 2
2113 | NC | 
2120 | A | 1
2120 | D | 2
2120 | NC | 
2120 | NC | NOTA
2130 | A | 1
2130 | A | 2a
2130 | D | 2b
2130 | NC | 
2130 | NC | 2
2140 | A | 
2140 | NC | NOTA
2150 | A | 1a
2150 | A | 2a
2150 | D | 2b
2150 | D | 1b
2150 | NC | 1
2150 | NC | 
2150 | NC | 2
2160 | A | 2a
2160 | D | 2b
2160 | D | 1b
2160 | E | 1a
2160 | NC | 2
2160 | NC | NOTA
2160 | NC | 1
2160 | NC | 
2170 | A | 1
2170 | D | 2
2170 | NC | 
2171 | D | 
2175 | D | 
2210 | A | 1
2210 | D | 2
2210 | D | 3
2210 | NC | NOTA
2210 | NC | 
2220 | D | 2b
2220 | D | 1b
2220 | E | 1a
2220 | E | 2a
2220 | NC | 2
2220 | NC | 1
2220 | NC | 
2221 | D | 2
2221 | E | 1
2221 | NC | 
2230 | D | 2
2230 | E | 1
2230 | NC | Nota
2230 | NC | 
2240 | A | A
2240 | D | B1b
2240 | D | B2b
2240 | E | B1a
2240 | E | B2a
2240 | NC | B1
2240 | NC | NOTA
2240 | NC | B
2240 | NC | B2
2240 | NC | 
2250 | A | 1
2250 | D | 3
2250 | E | 2
2250 | NC | NOTA
2250 | NC | 
2251 | A | A
2251 | D | B2
2251 | E | B1
2251 | NC | B
2251 | NC | 
2260 | D | 2b
2260 | D | 1b
2260 | E | 2a
2260 | E | 1a
2260 | NC | 1
2260 | NC | 
2260 | NC | 2
2265 | A | 1
2265 | D | 2
2265 | NC | 
2275 | A | 1
2275 | D | 2
2275 | NC | 
2311 | A | 1
2311 | D | 2
2311 | NC | 
2315 | A | 
2321 | D | 
2330 | A | 1
2330 | D | 2
2330 | NC | 
2340 | D | 2
2340 | E | 1
2340 | NC | 
2345 | A | 1
2345 | D | 2
2345 | NC | 
2345 | NC | NOTA
2350 | A | a
2350 | D | b
2350 | NC | 
2351 | A | 1
2351 | D | 2
2351 | NC | 
2355 | D | 
2360 | A | 1
2360 | D | 2
2360 | NC | 
2410 | D | 2
2410 | E | 1
2410 | NC | 
2415 | A | 1
2415 | D | 2
2415 | NC | 
2420 | A | 1
2420 | A | 2a
2420 | D | 2b
2420 | NC | 
2420 | NC | 2
2430 | A | a
2430 | D | b
2430 | NC | 
2440 | D | 
2445 | A | 1
2445 | D | 2
2445 | NC | 
2450 | A | Ba
2450 | A | Aa
2450 | D | Bb
2450 | D | Ab
2450 | NC | B
2450 | NC | Nota
2450 | NC | 
2450 | NC | A
2510 | A | 1
2510 | A | 4
2510 | A | 3
2510 | D | 6
2510 | D | 5
2510 | NC | 
2510 | NC | 2
2515 | D | 2b
2515 | D | 1b
2515 | E | 2a
2515 | E | 1a
2515 | NC | 1
2515 | NC | 
2515 | NC | 2
2516 | D | 2
2516 | E | 1
2516 | NC | 
2517 | D | 2
2517 | E | 1
2517 | NC | 
2518 | D | b
2518 | E | a
2518 | NC | 
2520 | A | 
2521 | D | 2b
2521 | E | 2a
2521 | E | 1
2521 | NC | 
2521 | NC | 2
2522 | D | b
2522 | E | a
2522 | NC | NOTA
2522 | NC | 
2523 | A | 
2524 | D | 
2530 | A | 2a
2530 | A | 1a
2530 | D | 2b
2530 | D | 1b
2530 | NC | 2
2530 | NC | 1
2530 | NC | 
2531 | A | a
2531 | D | b
2531 | NC | 
2540 | A | 
2541 | A | 
2541 | NC | 
2545 | A | 
2546 | A | a
2546 | D | b
2546 | NC | 
2547 | A | 
2550 | A | 1
2550 | D | 2
2550 | NC | 
2551 | A | 1
2551 | D | 2
2551 | NC | 
2552 | A | 1
2552 | D | 2
2552 | NC | 
2560 | D | 2
2560 | E | 1
2560 | NC | 
2561 | D | 
2562 | A | 1
2562 | D | 2
2562 | NC | 
2563 | D | 2
2563 | E | 1
2563 | NC | 
2564 | D | 1c
2564 | D | 2
2564 | D | 1b
2564 | E | 1a
2564 | NC | 1
2564 | NC | 
2565 | D | 2b
2565 | D | 4
2565 | D | 3
2565 | E | 1b
2565 | E | 1a
2565 | E | 2a
2565 | NC | 
2565 | NC | 2
2565 | NC | 1
2566 | A | 1a
2566 | A | 2
2566 | D | 1b
2566 | NC | 1
2566 | NC | 
2567 | A | 1a
2567 | A | 2a
2567 | D | 2b
2567 | D | 1b
2567 | NC | 1
2567 | NC | 
2567 | NC | 2
2570 | A | 1a
2570 | D | 2
2570 | D | 1b
2570 | NC | 1
2570 | NC | 
2575 | D | 
2630 | A | a
2630 | D | b
2630 | NC | 
2631 | A | 1
2631 | D | 2
2631 | NC | 
2640 | A | a
2640 | D | b
2640 | NC | 
2660 | A | a
2660 | D | b
2660 | NC | 
2661 | A | 1a
2661 | D | 2b
2661 | D | 1c
2661 | E | 1b
2661 | E | 2a
2661 | NC | 
2661 | NC | 2
2661 | NC | 1
2662 | D | 2
2662 | E | 1
2662 | NC | 
2663 | D | 2b
2663 | D | 1b
2663 | E | 2a
2663 | E | 1a
2663 | NC | 1
2663 | NC | 
2663 | NC | 2
2670 | A | 
2680 | A | 2
2680 | D | 1
2680 | NC | 
2680 | NC | NOTA
2681 | A | 
2690 | A | 2
2690 | D | 1
2690 | NC | 
2710 | A | 1a
2710 | D | 2b
2710 | D | 1b
2710 | E | 2a
2710 | NC | 1
2710 | NC | 
2710 | NC | 2
2711 | D | 2
2711 | E | 1
2711 | NC | 
2712 | A | 2
2712 | E | 3a
2712 | E | 1
2712 | E | 3b
2712 | NC | 
2712 | NC | 3
2713 | D | 2
2713 | E | 1
2713 | NC | 
2714 | D | 2
2714 | E | 1
2714 | NC | 
2715 | D | 
2716 | D | 2
2716 | E | 1
2716 | NC | 
2718 | A | 1
2718 | D | 2
2718 | NC | 
2719 | D | 
2720 | A | 1
2720 | A | 2
2720 | NC | 
2730 | A | 
2731 | A | 2
2731 | E | 1
2731 | NC | 
2740 | A | 
2750 | A | 
2751 | A | 
2752 | A | 
2760 | A | 2b
2760 | A | 4
2760 | A | 1
2760 | E | 3
2760 | E | 2a
2760 | NC | 
2760 | NC | 2
2770 | A | 
2771 | A | 
2780 | A | 2a
2780 | A | 3a
2780 | A | 1a
2780 | D | 2c
2780 | D | 1c
2780 | E | 2b
2780 | E | 3b
2780 | E | 1b
2780 | NC | 1
2780 | NC | 
2780 | NC | 2
2780 | NC | 3
2781 | A | 1a
2781 | A | 2a
2781 | D | 1c
2781 | E | 2b
2781 | E | 1b
2781 | NC | 1
2781 | NC | 
2781 | NC | 2
2782 | A | 
2790 | A | 
2791 | A | 1
2791 | D | 2
2791 | NC | 
2792 | A | 2
2792 | A | 1a
2792 | D | 1b
2792 | NC | NOTA
2792 | NC | 1
2792 | NC | 
2793 | A | 1a
2793 | A | 3b
2793 | A | 2a
2793 | D | 2b
2793 | D | 1b
2793 | D | 3a
2793 | D | 1c
2793 | NC | 1
2793 | NC | 
2793 | NC | Nota
2793 | NC | 2
2793 | NC | 3
2794 | D | 2
2794 | E | 1
2794 | NC | 
2795 | A | 1
2795 | D | 2
2795 | NC | 
2797 | A | 2
2797 | A | 1
2797 | NC | Nota
2797 | NC | 
2798 | D | 
2910 | A | B2
2910 | D | A2
2910 | E | B1
2910 | E | A1
2910 | NC | NOTA
2910 | NC | 
2910 | NC | B
2910 | NC | A
2915 | D | 1b
2915 | D | 2
2915 | E | 1a
2915 | NC | 
2915 | NC | 1
2921 | D | b
2921 | E | a
2921 | NC | 
2925 | D | 2
2925 | D | 1
2925 | NC | 
2925 | NC | NOTA
2930 | D | 2b
2930 | D | 1b
2930 | E | 1a
2930 | E | 2a
2930 | NC | 1
2930 | NC | 
2930 | NC | 2
2931 | A | 1
2931 | A | 2
2931 | NC | 
2931 | NC | Nota
2940 | D | 3b
2940 | D | 2b
2940 | D | 1b
2940 | E | 1a
2940 | E | 2a
2940 | E | 3a
2940 | NC | 2
2940 | NC | Nota
2940 | NC | 3
2940 | NC | 1
2940 | NC | 
2950 | A | 2a
2950 | A | 1a
2950 | D | 2b
2950 | D | 1b
2950 | NC | 1
2950 | NC | 
2950 | NC | 2
2960 | A | 
2970 | A | 
2971 | A | 1)
2971 | A | 2)
2971 | NC | 
2980 | A | 1
2980 | A | 2a
2980 | D | 2b
2980 | NC | 
2980 | NC | 2
3110 | A | 
3120 | A | 
3130 | A | 
3140 | A | a
3140 | A | b
3140 | NC | 
3210 | A | 
3220 | A | 
3230 | A | b
3230 | A | a
3230 | A | c
3230 | NC | 
3240 | A | 
3250 | A | 2b
3250 | A | 3a
3250 | A | 2c
3250 | A | 1
3250 | A | 3b
3250 | A | 2a
3250 | A | 3c
3250 | NC | NOTA
3250 | NC | 
3250 | NC | 3
3250 | NC | 2
3260 | A | 
3310 | A | 1b
3310 | A | 1a
3310 | A | 2
3310 | A | 3
3310 | NC | 1
3310 | NC | 
3330 | A | 
3340 | A | 
3350 | A | 
3410 | A | g
3410 | A | j
3410 | A | h
3410 | A | d
3410 | A | i
3410 | A | a
3410 | A | c
3410 | A | e
3410 | A | f
3410 | A | k
3410 | A | b
3410 | NC | 
3420 | A | d
3420 | A | a
3420 | A | e
3420 | A | b
3420 | A | c
3420 | NC | 
3430 | A | 
3440 | A | 
3450 | A | 
3460 | A | 
3510 | A | 
3520 | A | b
3520 | A | a
3520 | NC | 
3531 | A | 
3532 | A | 
3540 | A | 2
3540 | A | 1
3540 | NC | 
3550 | A | 
3560 | A | 
3610 | A | a
3610 | A | b
3610 | A | c
3610 | NC | 
3620 | A | 
3630 | A | 
3641 | A | 
3642 | A | 3b
3642 | A | 1
3642 | A | 2a
3642 | A | 3a
3642 | A | 2b
3642 | NC | Nota
3642 | NC | 2
3642 | NC | 3
3642 | NC | 
3643 | A | 
3650 | A | 
3660 | A | a
3660 | A | c
3660 | A | b
3660 | NC | Nota
3660 | NC | 
3670 | A | 1
3670 | A | 2
3670 | NC | 
3680 | A | 
3690 | A | 
3700 | A | 
3710 | A | 
4000 | NC | 
4001 | A | 
4110 | A | 2a
4110 | A | 3a
4110 | A | 1a
4110 | D | 2b
4110 | D | 3b
4110 | D | 1b
4110 | NC | 2
4110 | NC | 3
4110 | NC | 1
4110 | NC | 
4120 | A | 3a
4120 | A | 1a
4120 | A | 2a
4120 | D | 2b
4120 | D | 1b
4120 | D | 3b
4120 | NC | 3
4120 | NC | 1
4120 | NC | 
4120 | NC | 2
4130 | A | 2a
4130 | A | 3a
4130 | A | 1a
4130 | D | 2b
4130 | D | 3b
4130 | D | 1b
4130 | NC | 1
4130 | NC | 
4130 | NC | 2
4130 | NC | 3
4140 | A | 1a
4140 | A | 2a
4140 | A | 3a
4140 | D | 2b
4140 | D | 3b
4140 | D | 1b
4140 | NC | 1
4140 | NC | 
4140 | NC | 2
4140 | NC | 3
4150 | A | 1
4150 | D | 2
4150 | NC | 
4210 | A | 1a
4210 | A | 2a
4210 | D | 2b
4210 | D | 1b
4210 | NC | 1
4210 | NC | 
4210 | NC | 2
4210 | NC | Nota
4220 | A | 1
4220 | D | 3
4220 | D | 4
4220 | E | 2
4220 | NC | Nota
4220 | NC | 
4240 | A | 2
4240 | A | 1
4240 | NC | 
4310 | A | 1
4310 | D | 2
4310 | NC | 
4320 | A | 1
4320 | D | 2
4320 | NC | Nota
4320 | NC | 
4321 | A | 1
4321 | D | 2
4321 | NC | Nota
4321 | NC | 
4330 | A | 1
4330 | D | 2
4330 | NC | 
4331 | A | 1
4331 | D | 3
4331 | E | 2
4331 | NC | 
4410 | A | 1
4410 | D | 2
4410 | NC | 
4411 | A | 1
4411 | D | 2
4411 | NC | 
4420 | A | 1
4420 | D | 2
4420 | NC | 
4421 | A | 1
4421 | D | 2
4421 | NC | 
4422 | A | 1
4422 | D | 2
4422 | NC | 
4430 | A | 
4431 | A | 
4440 | A | 1
4440 | D | 2
4440 | NC | 
4441 | A | 1
4441 | D | 2
4441 | NC | 
4442 | A | 1
4442 | D | 2
4442 | NC | 
4510 | A | 1
4510 | D | 2
4510 | NC | 
4511 | A | 1
4511 | D | 2
4511 | NC | 
4610 | A | 1
4610 | D | 2
4610 | NC | 
4620 | A | 1
4620 | D | 2
4620 | NC | 
4630 | A | 1
4630 | D | 2
4630 | NC | 
4701 | A | 1a
4701 | A | 2a
4701 | D | 2b
4701 | D | 1b
4701 | NC | 1
4701 | NC | 
4701 | NC | 2
4702 | A | IIIIIIa
4702 | D | IIIIIIb
4702 | D | IIIIIIc
4702 | D | IV
4702 | NC | IIIIII
4702 | NC | Nota
4702 | NC | 
4703 | A | 
4705 | A | 1
4705 | D | 2
4705 | NC | 
4706 | A | 1
4706 | D | 2
4706 | NC | 
4707 | A | 1
4707 | D | 2
4707 | NC | 
4708 | A | 
4709 | A | 1
4709 | D | 2
4709 | NC | 
4710 | A | 1
4710 | D | 2
4710 | NC | 
4711 | A | 1
4711 | D | 2
4711 | NC | 
4712 | A | 
4713 | A | 1
4713 | D | 2
4713 | NC | 
4714 | A | 1
4714 | D | 2
4714 | NC | 
4715 | A | 1
4715 | D | 2
4715 | NC | 
4716 | A | 1
4716 | D | 2
4716 | NC | 
4717 | A | 1
4717 | D | 2
4717 | NC | 
4718 | A | 1a
4718 | A | 2a
4718 | D | 2b
4718 | D | 1b
4718 | NC | 1
4718 | NC | NOTA
4718 | NC | 
4718 | NC | 2
4719 | A | 1
4719 | D | 2
4719 | NC | 
4720 | A | 1
4720 | D | 2
4720 | NC | 
4721 | A | 1
4721 | D | 2
4721 | NC | 
4722 | A | 1
4722 | D | 2
4722 | NC | 
4723 | A | 1
4723 | D | 2
4723 | NC | 
4724 | A | 1
4724 | D | 2
4724 | NC | 
4725 | A | 1
4725 | D | 2
4725 | NC | 
4726 | A | 1
4726 | D | 2
4726 | NC | 
4727 | A | 1
4727 | D | 2
4727 | NC | 
4728 | A | 1
4728 | D | 2
4728 | NC | 
4729 | A | 1
4729 | D | 2
4729 | NC | 
4730 | A | 1
4730 | D | 2
4730 | NC | 
4731 | A | 1
4731 | D | 2
4731 | NC | 
4732 | A | 1
4732 | D | 2
4732 | NC | 
4733 | A | 1
4733 | D | 2
4733 | NC | 
4734 | A | 2a
4734 | A | 1a
4734 | D | 1c
4734 | D | 2c
4734 | E | 2b
4734 | E | 1b
4734 | NC | 2
4734 | NC | 1
4734 | NC | 
4735 | A | 2a
4735 | A | 1a
4735 | D | 2b
4735 | D | 1b
4735 | NC | 1
4735 | NC | 
4735 | NC | 2
4736 | A | 1
4736 | D | 2
4736 | NC | 
4737 | A | 1
4737 | D | 2
4737 | NC | 
4738 | A | 1
4738 | D | 2
4738 | NC | 
4739 | A | 1
4739 | D | 2
4739 | NC | 
4740 | A | 1
4740 | D | 2
4740 | NC | 
4741 | A | 1
4741 | D | 2
4741 | NC | 
4742 | A | 1
4742 | D | 2
4742 | NC | 
4743 | A | 1
4743 | D | 2
4743 | NC | 
4744 | A | 1
4744 | D | 2
4744 | NC | 
4745 | A | 1
4745 | D | 2
4745 | NC | 
4746 | A | 1
4746 | D | 2
4746 | NC | 
4747 | A | 1
4747 | D | 2
4747 | NC | 
4748 | A | 1
4748 | D | 2
4748 | NC | 
4749 | A | 
4755 | A | 1
4755 | A | 2a
4755 | D | 2b
4755 | NC | 
4755 | NC | 2
4801 | A | 1
4801 | D | 2
4801 | NC | 

</details>

**NB** : Tous les classements en vigueur des installations de la base ne sont pas dans cette liste. En effet, il y a certains classements qui correspondent à des rubriques supprimés. 91% des classements avec une A, E ou D de la base sont contenus dans cette liste.

**Proposition** : se servir de cette liste uniquement pour préremplir les champs avec autocomplétion, mais ne pas contraindre la modification des classements (pour gérer les cas où la nomenclature évolue mais n'est pas encore à jour sur Envinorma par exemple, ou bien pour permettre à l'utilisateur de changer l'alinéa)
