### ISSUE TITLE
[Nouvelle Installation] créer le lien depuis la page d'accueil pour créer une nouvelle installation

### ISSUE THREAD

**Issue by lisa-durand** [Envinorma/envinorma-web#179]

**Comment by remidbs** [comment]
En terme d’usage, il me semblait logique de :
- rediriger sur la page de modification du nom de l’installation créée plutôt que sur l’onglet de création d’un classement, sinon on comprend pas bien qu’une installation a été créée je trouve
- enlever le bouton “Modifier les classements” si pas de classements
